### ISSUE TITLE
Bad yaml file

### ISSUE THREAD

**Issue by claudiocabral** [saunaklub/etudes#9]
On OS X etudes-host terminates with the following exception in branches `master` and `elements`:
`libc++abi.dylib: terminating with uncaught exception of type YAML::BadFile: bad file
Abort trap: 6`

**Comment by drlight-code** [comment]
I suppose you need to start from the toplevel directory, for now it looks for 'configuration/host.yml', so what I do is './build/etudes-host'.

**Comment by drlight-code** [comment]
We should catch the badfile exception there and print the (relative) path where the config is searched to make that more obvious. In the long term, when the application is deployed properly, we need some default config location in the user's home directory which can be overridden by an environment or command line setting.

**Comment by claudiocabral** [comment]
confirm that this was the issue, gonna implement the exception capturing now
